// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2MjR_1lXpMOW-9fpFZYuFpRQWrjvY5A',
    appId: '1:975996341660:web:1e3702b347109cff8a4c59',
    messagingSenderId: '975996341660',
    projectId: 'elevateu-1fa00',
    authDomain: 'elevateu-1fa00.firebaseapp.com',
    storageBucket: 'elevateu-1fa00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCwxJ8yBSJZf0tvMyGG_KQd7-_dwlLZE',
    appId: '1:975996341660:android:208d8ebb7e796e278a4c59',
    messagingSenderId: '975996341660',
    projectId: 'elevateu-1fa00',
    storageBucket: 'elevateu-1fa00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57qCg67V79ScSPNC_f6N2mHzpstTLvB4',
    appId: '1:975996341660:ios:7337df48e7d14dde8a4c59',
    messagingSenderId: '975996341660',
    projectId: 'elevateu-1fa00',
    storageBucket: 'elevateu-1fa00.firebasestorage.app',
    iosBundleId: 'com.example.collegeProject',
  );
}
